### ISSUE TITLE
Possible to use with Compose Previews?

### ISSUE THREAD

**Issue by ianthetechie** [ramani-maps/ramani-maps#33]
I'm curious if Ramani Maps is usable in Compose Previews. I have attempted to set up an extremely simple view, but am not having any luck with it.

<img width="738" alt="image" src="https://github.com/ramani-maps/ramani-maps/assets/2140440/d68f5425-60fb-4c16-8976-91ae55669585">

I suspect that the issue might be that Compose Previews don't work due to some specific features used in MapLibre / Mapbox. There is a related discussion upstream here: https://github.com/maplibre/maplibre-native/issues/344#issuecomment-1842109783.

**Comment by JonasVautherin** [comment]
Oh that's a good question, we haven't tried that. I am following the discussion upstream, but please keep us posted if you find something! It would be great if Ramani supported Compose previews :+1:.

**Comment by ianthetechie** [comment]
Thanks; will do!

**Comment by JonasVautherin** [comment]
I am not sure if this is a ramani issue or a maplibre issue (does the preview work with maplibre-android?), but I don't think anyone is planning on working on this here.

So I'll just close it, but anyone is free to reopen it if they want to add more information / work on it.

**Comment by ianthetechie** [comment]
Yeah... it's a problem but I also don't know whether it's a MapLibre Native issue, Jetpack Compose issue, etc. so it's fine to close this. I'll write back here if I ever get back to this and find a solution.
