### ISSUE TITLE
Support other tile providers

### ISSUE THREAD

**Issue by ianthetechie** [ramani-maps/ramani-maps#34]
At the moment, Ramani Maps only works with MapTiler. However, MapLibre uses an open tile format which is available from others, including Stadia Maps (another founding member of MapLibre) and Mapbox (you may still choose MapLibre if you want a FOSS tile renderer). We can easily improve the interface to be more flexible.

**Comment by klemensz** [comment]
Hi! I'd like to use the MapLibre implementation with a custom styleUrl. It looks like this is not available in the latest release version yet?

**Comment by JonasVautherin** [comment]
I was not expecting it to be needed that quickly, but that's good :blush:. I just published [`0.2.0`](https://github.com/ramani-maps/ramani-maps/releases/tag/maplibre-0.2.0) to Maven, it should be available in a couple of hours.

Let me know if it doesn't! :innocent:

**Comment by JonasVautherin** [comment]
Actually it is already available, I think: https://central.sonatype.com/artifact/org.ramani-maps/ramani-maplibre/0.2.0. @klemensz: would you mind trying it and letting us know if it works?

**Comment by klemensz** [comment]
I tried it and it works! Thanks for the quick action!

Now I got another topic for which I created an issue [here](https://github.com/ramani-maps/ramani-maps/issues/39) 🙂
