### ISSUE TITLE
Possibility to modify map's uiSettings 

### ISSUE THREAD

**Issue by klemensz** [ramani-maps/ramani-maps#39]
I haven't found a way to modify to modify the `uiSetting` like in this example, where I directly use the MapLibre SDK:

```kt
@Composable
fun MapView() {
    val topPadding = with(LocalDensity.current) {
        WindowInsets.statusBars.getTop(this)
    }
    AndroidView(
        factory = { context ->
            Mapbox.getInstance(context)
            val mapView = com.mapbox.mapboxsdk.maps.MapView(context)
            val styleUrl = "https://my-style-url-here"
            mapView.onCreate(null)
            mapView.getMapAsync { map ->
                map.uiSettings.setCompassMargins(0, topPadding, 0, 0) // <-- access to uiSettings
                map.setStyle(styleUrl) {
                    map.cameraPosition = Builder()
                        .target(LatLng(46.0, 4.8))
                        .zoom(10.0)
                        .bearing(2.0)
                        .build()
                }
            }
            mapView
        },
    )
}
```

I need this because otherwise the compass will overlay the top status bar in "[edge-to-edge](https://developer.android.com/jetpack/compose/layouts/insets)" mode.

![screenshot_compass](https://github.com/ramani-maps/ramani-maps/assets/1116517/8416f94f-2a38-435f-92e7-a9e8b6bcd2e6)

**Comment by JonasVautherin** [comment]
Thanks for the clear feature request! We don't have that yet, but there is definitely a need for it. I think we should wrap the settings into our own object (`MaplibreSettings` or `UiSettings` or something) and enable hoisting with it.

I'll try to have a look ASAP, it should not be a very big task :+1:.

**Comment by klemensz** [comment]
Great! I'd be happy to test it as soon as it's available.

**Comment by klemensz** [comment]
There are some additional related properties or settings that are currently not accessible:
* `setMaxZoomPreference()` - prevent the user from zooming in too much, for example if the map isn't detailed enough
* `locationComponent` - needed to show the [user's current location](https://maplibre.org/maplibre-native/docs/book/android/location-component-guide.html)

**Comment by JonasVautherin** [comment]
@klemensz: I already added the first one (CompassMargins) in #42. Would you mind reviewing/testing? Other settings will follow, but that's a first try :blush:.

**Comment by JonasVautherin** [comment]
I think we now have all the features explicitly required in this issue, so I will close it. As mentioned, not all the settings of MapLibre are exposed, but now we have a structure and it should be easy to add new features one at a time (e.g. `setMinZoomPreference()` should be trivial to contribute for anyone needing it).

Feel free to open new issues if you find a bug in those features or if you need new ones, of course :blush:.
