### ISSUE TITLE
Support for clustering (CircleLayer)

### ISSUE THREAD

**Issue by klemensz** [ramani-maps/ramani-maps#40]
The clustering of POIs (or symbols, pins) is - from my point of view - an essential feature for many apps that need to display a lot of POIs on a map.

![Map Clustering Screenshot](https://github.com/ramani-maps/ramani-maps/assets/1116517/033e30fc-566a-4b03-a43c-de2bb8283ab5)

Examples:
- https://docs.mapbox.com/android/legacy/maps/examples/circle-layer-clustering/
- https://maplibre.org/maplibre-gl-js/docs/examples/cluster/

It's also possible to use SymbolLayer for clustering, but it's more complicated, see https://docs.mapbox.com/android/legacy/maps/guides/clustering/ for a comparison.

**Comment by JonasVautherin** [comment]
@klemensz actually do you need this in an app now or was it more of a general suggestion for Ramani?

**Comment by ravenfeld** [comment]
In my case, I no longer use Ramanu because it doesn't meet my needs for cluster management. The localization puck too, in short I took the basics but coded it myself.

**Comment by JonasVautherin** [comment]
> in short I took the basics but coded it myself.

@ravenfeld: Is that open source somewhere? I would love to have a look at how you did it. BTW we would have gladly taken pull requests, and in the meantime we did implement the location (and clusters are coming soon) :innocent:.
