### ISSUE TITLE
MapLibre: Logcat many error "PIXEL: ioctl err: 1" on Pixel 7

### ISSUE THREAD

**Issue by ravenfeld** [ramani-maps/ramani-maps#41]
Hello, I'm asking for your help because I don't understand the problem.
Everything works fine, but my logcat gets killed by this log "PIXEL: ioctl err: 1" every 12 ms

Thanks in advance

**Comment by JonasVautherin** [comment]
Can you copy the full line? Where does it come from? I don't think Ramani prints that, it probably comes from Maplibre. Would be nice to understand why, though.

**Comment by ravenfeld** [comment]
![Capture d’écran 2024-01-06 à 12 10 20](https://github.com/ramani-maps/ramani-maps/assets/3765114/8f56ca52-c229-44f2-adc1-7d60893609ec)
I also think it's MapLibre, I'm making an xml project to compare.

**Comment by ravenfeld** [comment]
For your information, I have the same problem with an xml version, but it's maplibre that's the problem.

**Comment by JonasVautherin** [comment]
Thanks for the report!
