### ISSUE TITLE
Will Ramani support new Maplibre annotations?

### ISSUE THREAD

**Issue by mtpdog** [ramani-maps/ramani-maps#61]
Hello,

I've found some new bugs in the current implementation of Ramani maps (e.g. Icons with text are not visible if mapbox style is applied, while Icons without text are visible, seems to be some layer ordering issue). However, I'm curious will Ramani Maps implement in the future some currently developing new annotations in Maplibre like this:
https://github.com/maplibre/maplibre-native/pull/1908
Images that scale and rotate with the map.

**Comment by JonasVautherin** [comment]
Sure, I think we are open to supporting the maplibre-native features in Ramani-Maps! This one is still in development there, right?

**Comment by mtpdog** [comment]
> Sure, I think we are open to supporting the maplibre-native features in Ramani-Maps! This one is still in development there, right?

Yes, you're right it is still in development. I hope it will be added when released. Thanks!

**Comment by JonasVautherin** [comment]
Let's open a feature request here when it is released in maplibre-native, I would say!
