### ISSUE TITLE
Text annotations are not visible with Mapbox style

### ISSUE THREAD

**Issue by mtpdog** [ramani-maps/ramani-maps#62]
I've added 4 types of annotations:
- Blue circles without text
- Red circles with text
- Symbols without text
- Symbols with text

> 

                        Circle(
                            center = LatLng(latStart + Math.random()/100, lonStart + Math.random()/100),
                            radius = 3.0F,
                            color = "Blue",
                            borderWidth = 0.5f,
                            borderColor = "White",
                            zIndex = 1,
                            isDraggable = false,
                        )

                        CircleWithItem(
                            center = LatLng(latStart + Math.random()/100, lonStart + Math.random()/100),
                            radius = 3.0F,
                            color = "Red",
                            borderWidth = 0.5f,
                            borderColor = "White",
                            zIndex = 2,
                            isDraggable = false,
                            textSize = 12.0f,
                            textColor = "Red",
                            text = "Text " + (Math.random()*100).toInt().toString()
                        )

                        Symbol(
                            center = LatLng(latStart + Math.random()/100, lonStart + Math.random()/100),
                            color = "Yellow",
                            zIndex = 3,
                            imageId = R.drawable.app_action_location_current_24,
                            iconSize = 1f,
                            isDraggable = false,
                            textSize = 1f
                        )

                        Symbol(
                            center = LatLng(latStart + Math.random()/100, lonStart + Math.random()/100),
                            color = "Black",
                            zIndex = 3,
                            imageId = R.drawable.app_action_temperature_24,
                            iconSize = 1f,
                            isDraggable = false,
                            textSize = 10.0f,
                            text = "Temp " + (Math.random()*100).toInt().toString()
                        )

1) When default MapLibre style is used all annotations are visible
`MapLibre(
                modifier = Modifier.fillMaxSize(),
                cameraPosition = cameraPosition.value
            )`

![default_style](https://github.com/ramani-maps/ramani-maps/assets/150581563/3cc969b8-29a4-4cb8-93ec-a1beb74ea2db)

2) When Mapbox Style is applied (you need to set Mapbox api key beforehand) some annotations are not visible anymore:
`            MapLibre(
                modifier = Modifier.fillMaxSize(),
                styleUrl = "mapbox://styles/mapbox/satellite-streets-v12",
                cameraPosition = cameraPosition.value
            )`

![mapbox_style](https://github.com/ramani-maps/ramani-maps/assets/150581563/69d4407c-af56-4557-a316-3c6fb920746e)

It can be seen that:
- Blue circles are visible (good)
- Red circles are visible but their labels disappeared (not good)
- Symbols with and without labels are both gone (bad)

zIndex doesn't seem to do anything.
I also tried to find the cause in the layering order but couldn't.

Can you help please?

**Comment by ianthetechie** [comment]
Hmm... not offhand.  MapLibre itself should have no issues rendering additional layers in a way that varies by style (that I'm aware of). Nor have I seen any issues so far with annotations on non-default styles in our limited use, BUT I confess I haven't tried text annotations in Ramai yet :D

I do have two really vague ideas though:

1. Does Ramani try to place annotations intelligently into an existing style?  For example, does it try to place text layers over certain base layers, or place shapes below labels?
2. It looks like these are symbol layers with custom images. I haven't tried this in our Android project yet, but I do know from the iOS side that symbol loading in MapLibre is a bit of a dance to get right.

Sorry that's not much to go on. I do need to add symbol layers to our project fairly soon though, so I'll see if I can reproduce. Might not be for a few days but if I'll post an update here.

**Comment by JonasVautherin** [comment]
> Does Ramani try to place annotations intelligently into an existing style?

Yes, it tries to create one layer for e.g. all the circles that have the same z-index. Apparently something is going wrong there depending on the style :thinking:.

**Comment by brane14** [comment]
Have same issue with mapbox style and rendering text symbols. Any progress on this issue?

**Comment by JonasVautherin** [comment]
Mapbox has shown that they are unwilling to help us support them. They made breaking API changes in minor releases that prevent Ramani-Maps from having interactive objects at all and they have generally ignored us. As a consequence, I am not willing to spend time trying to support Mapbox anymore.

Have you considered using MapLibre?

**Comment by brane14** [comment]
Tried also with Maplibre and have same issue

**Comment by brane14** [comment]
Found problem in my case... font used in my style was missing. 
Solved it by adding `withTextFont()` to `SymbolOptions`

**Comment by JonasVautherin** [comment]
@mtpdog could it be the same problem for you as well?

**Comment by mtpdog** [comment]
> @mtpdog could it be the same problem for you as well?

Yes. This was the issue. Font was absent in the style.
