### ISSUE TITLE
Support camera tracking modes on locationComponent

### ISSUE THREAD

**Issue by torrybr** [ramani-maps/ramani-maps#72]
Support setting different camera modes as defined here -> https://docs.mapbox.com/android/legacy/maps/guides/location-component/#cameramode

Use Case: I want the camera to follow my blue dot as it moves around / I want the map to zoom to my dot when i click a button by using the camera mode options

**Comment by JonasVautherin** [comment]
Feel free to extend [this location example](https://github.com/ramani-maps/ramani-maps/blob/main/examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt) if you think it makes sense! I would love to be able to try it there!
