### ISSUE TITLE
Is there a way to use a styleJSON directly?

### ISSUE THREAD

**Issue by EllisGlaeser** [ramani-maps/ramani-maps#82]
Currently we are using Map Libre native for Android, but I am looking into Ramani. My problem is that we build style JSONs that we then send to Map Libre using `Style.Builder().fromJson(styleJson.toString())`. 
Since ramani's `MapLibre` composable is expecting a URL, I don't see a way currently to use this type of style. Am I correct? Is this something that is planned to add?

**Comment by JonasVautherin** [comment]
So currently we call [`setStyle(styleUrl)`](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibreCompose.kt#L64), right?

Is there an equivalent `setStyle(style)` that takes a `Style` (which you can build with `Style.Builder().fromJson(styleJson.toString())`)?

Also is there a `Style.Builder().fromUrl(styleUrl)`? I am now wondering if instead of [`styleUrl`](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L92) Ramani should maybe take a `style`? 🤔 

What do you think?

**Comment by EllisGlaeser** [comment]
@JonasVautherin There's `setStyle(styleUrl)`, and the other method is `setStyle(Style.Builder)`. How I'm doing it is I create a `Style.Builder` from the JSON that I create.

There is a `Style.Builder().fromUri()` that I assume would take the styleUrl, but I am not positive on that.

**Comment by JonasVautherin** [comment]
> There is a Style.Builder().fromUri() that I assume would take the styleUrl, but I am not positive on that.

Would you mind confirming that? Then maybe I could change the `MapLibre` composable to take a `Style.Builder` instead of a `String`... I think it would make sense...

**Comment by EllisGlaeser** [comment]
Ah, yep it just calls `setStyle(Style.Builder().fromUri(styleUrl)` behind the scenes when you pass the styleUrl. Here are the methods from the source code:

```java
public void setStyle(String style) {
        this.setStyle((String)style, (Style.OnStyleLoaded)null);
    }

    public void setStyle(String style, Style.OnStyleLoaded callback) {
        this.setStyle((new Style.Builder()).fromUri(style), callback);
    }

    public void setStyle(Style.Builder builder) {
        this.setStyle((Style.Builder)builder, (Style.OnStyleLoaded)null);
    }

    public void setStyle(Style.Builder builder, Style.OnStyleLoaded callback) {
        this.styleLoadedCallback = callback;
        this.locationComponent.onStartLoadingMap();
        if (this.style != null) {
            this.style.clear();
        }

        this.style = builder.build(this.nativeMapView);
        if (!TextUtils.isEmpty(builder.getUri())) {
            this.nativeMapView.setStyleUri(builder.getUri());
        } else if (!TextUtils.isEmpty(builder.getJson())) {
            this.nativeMapView.setStyleJson(builder.getJson());
        } else {
            this.nativeMapView.setStyleJson("{\"version\": 8,\"sources\": {},\"layers\": []}");
        }

    }
```

**Comment by JonasVautherin** [comment]
Would you mind trying and reviewing https://github.com/ramani-maps/ramani-maps/pull/84?
