### ISSUE TITLE
Issues when trying to work on a fork

### ISSUE THREAD

**Issue by EllisGlaeser** [ramani-maps/ramani-maps#86]
This may just be my ignorance showing regarding GitHub/Android Studio, but when I created a fork of Ramani and open it up in Android Studio to work on it, there is no error highlighting, even though the settings seem to all be correct. Is there something in the project itself that is disabling this, or is there another way to fix this that you know of?

Also, when I look at the build.gradle.kts file, it says "Code insight unavailable (related Gradle project not linked).", with a button saying "Link Gradle Project". Does that have anything to do with the problem?

**Comment by JonasVautherin** [comment]
It is a completely standard Gradle project, nothing disables anything 😊. You may try to build from CLI to check that it works in your environment with `./gradlew build`.

**Comment by EllisGlaeser** [comment]
Ah, it's working now. I think I just missed a step :P
