### ISSUE TITLE
Removing layer from loaded map style

### ISSUE THREAD

**Issue by klemensz** [ramani-maps/ramani-maps#89]
I have a requirement to remove an existing layer that is part of the default style loaded into a MapLibre map. Specifically, I need to remove layers whose IDs start with "xyz" for example. Below is a simplified example of how I am currently achieving this in a View-based Android app:

```kotlin
    mapboxMap?.style?.apply { style ->
        style.layers.forEach {
            if (it.id.startsWith("xyz")) {
                style.removeLayer(it)
            }
       }
   }
```

I am now trying to implement this with Ramani maps and haven’t found a way to replicate this functionality. Could you please advise if this is currently possible? If so, could you provide some guidance or examples?

Thank you for your assistance!

**Comment by JonasVautherin** [comment]
The `MapLibre` element of Ramani now takes a `StyleBuilder`: https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L92-L93. Is it possible to achieve that with a style builder?

**Comment by klemensz** [comment]
I have't found a way how to do it with `StyleBuilder`. I can remove a layer from `Style`, but not from `StyleBuilder`. It's possible to add a layer (`withLayer()` or similar functions) but not to remove one.

**Comment by JonasVautherin** [comment]
Is it a lot more efficient for MapLibre-native to use `style.removeLayer` than to reload a new style entirely? It is currently possible to swap the style (e.g. between satellite photos to vector map) like this. Could you provide a new `StyleBuilder` that would build a new style that doesn't have the layers you don't want?

**Comment by klemensz** [comment]
How can I get access to the loaded style? The style that I need to load via the Uri contains a set of layers of which I need to remove one. But within the `Style.Builder` these are not known.

**Comment by klemensz** [comment]
I created a PR (#92) with a possible solution for this - let me know what you think.

**Comment by JonasVautherin** [comment]
I haven't forgotten it, I just would like to make a few tests and the last few weeks have been busy. I'm hoping to get back to this during next week!
