### ISSUE TITLE
Support for setting custom LocationEngine (MapLibre)

### ISSUE THREAD

**Issue by klemensz** [ramani-maps/ramani-maps#96]
Is this currently possible somehow? See this (MapBox) example:

```kotlin
 val locationComponentOptions = LocationComponentOptions.builder(requireContext())
  .bearingTintColor(R.color.colorPrimary).backgroundTintColor(R.color.colorPrimary)
  .build()
 val locationComponentActivationOptions = LocationComponentActivationOptions
  .builder(requireContext(), style)
  .locationComponentOptions(locationComponentOptions)
  .locationEngine(locationEngine) // <- SETTING LOCATION ENGINE
  .build()
mapboxMap.locationComponent.activateLocationComponent(locationComponentActivationOptions)
```

**Comment by JonasVautherin** [comment]
I believe we currently use the default location engine: https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L240.

Feels like it wouldn't be difficult to expose it to [`MapLibre`](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L90) and forward it [here](https://github.com/ramani-maps/ramani-maps/blob/main/ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt#L140) 🤔. What do you think?
